import 'package:sello/shared/models/report_models.dart';

/// Static catalog of report questions — UI navigation, not data.
abstract final class ReportCatalog {
  static const definitions = <ReportDefinition>[
    // Sales
    ReportDefinition(
      id: 'sales_daily',
      category: ReportCategory.sales,
      title: 'Daily sales',
      question: 'How much did we sell today and recently?',
      icon: 'trending_up',
    ),
    ReportDefinition(
      id: 'sales_monthly',
      category: ReportCategory.sales,
      title: 'Monthly sales',
      question: 'What is revenue for this month?',
      icon: 'calendar_month',
    ),
    ReportDefinition(
      id: 'sales_trend',
      category: ReportCategory.sales,
      title: 'Sales trend',
      question: 'Is sales rising or falling over the period?',
      icon: 'show_chart',
    ),
    ReportDefinition(
      id: 'sales_aov',
      category: ReportCategory.sales,
      title: 'Average order value',
      question: 'What is a typical completed order worth?',
      icon: 'payments',
    ),
    ReportDefinition(
      id: 'sales_top_products',
      category: ReportCategory.sales,
      title: 'Top selling products',
      question: 'Which products drive the most revenue?',
      icon: 'inventory_2',
    ),
    ReportDefinition(
      id: 'sales_top_categories',
      category: ReportCategory.sales,
      title: 'Top categories',
      question: 'Which categories sell best?',
      icon: 'category',
    ),
    ReportDefinition(
      id: 'sales_top_reps',
      category: ReportCategory.sales,
      title: 'Top sales representatives',
      question: 'Who closes the most business this period?',
      icon: 'badge',
    ),
    // Customers
    ReportDefinition(
      id: 'customers_top',
      category: ReportCategory.customers,
      title: 'Top customers',
      question: 'Who buys the most in this period?',
      icon: 'groups',
    ),
    ReportDefinition(
      id: 'customers_frequency',
      category: ReportCategory.customers,
      title: 'Purchase frequency',
      question: 'How often do top customers order?',
      icon: 'repeat',
    ),
    ReportDefinition(
      id: 'customers_outstanding',
      category: ReportCategory.customers,
      title: 'Outstanding balances',
      question: 'Who still owes us money?',
      icon: 'account_balance_wallet',
    ),
    ReportDefinition(
      id: 'customers_recent',
      category: ReportCategory.customers,
      title: 'Recent customers',
      question: 'Who joined in the last 30 days?',
      icon: 'person_add',
    ),
    ReportDefinition(
      id: 'customers_inactive',
      category: ReportCategory.customers,
      title: 'Inactive customers',
      question: 'Who has not purchased recently?',
      icon: 'person_off',
    ),
    // Products
    ReportDefinition(
      id: 'products_best',
      category: ReportCategory.products,
      title: 'Best sellers',
      question: 'Which products move the most?',
      icon: 'star',
    ),
    ReportDefinition(
      id: 'products_categories',
      category: ReportCategory.products,
      title: 'Category mix',
      question: 'How is sales split across categories?',
      icon: 'pie_chart',
    ),
    // Inventory
    ReportDefinition(
      id: 'inventory_stock',
      category: ReportCategory.inventory,
      title: 'Current stock',
      question: 'How many SKUs are on hand?',
      icon: 'warehouse',
    ),
    ReportDefinition(
      id: 'inventory_value',
      category: ReportCategory.inventory,
      title: 'Stock value',
      question: 'What is inventory worth at cost?',
      icon: 'attach_money',
    ),
    ReportDefinition(
      id: 'inventory_low',
      category: ReportCategory.inventory,
      title: 'Low stock',
      question: 'Which items need reorder attention?',
      icon: 'warning_amber',
    ),
    ReportDefinition(
      id: 'inventory_out',
      category: ReportCategory.inventory,
      title: 'Out of stock',
      question: 'What cannot be sold right now?',
      icon: 'remove_shopping_cart',
    ),
    ReportDefinition(
      id: 'inventory_fast',
      category: ReportCategory.inventory,
      title: 'Fast moving products',
      question: 'What is selling through quickly?',
      icon: 'speed',
    ),
    ReportDefinition(
      id: 'inventory_slow',
      category: ReportCategory.inventory,
      title: 'Slow moving products',
      question: 'What is sitting in stock?',
      icon: 'hourglass_bottom',
      available: false,
    ),
    ReportDefinition(
      id: 'inventory_adjustments',
      category: ReportCategory.inventory,
      title: 'Recent adjustments',
      question: 'What stock movements happened lately?',
      icon: 'sync_alt',
    ),
    // Payments
    ReportDefinition(
      id: 'payments_paid',
      category: ReportCategory.payments,
      title: 'Paid orders',
      question: 'How many completed orders are fully paid?',
      icon: 'check_circle',
    ),
    ReportDefinition(
      id: 'payments_partial',
      category: ReportCategory.payments,
      title: 'Partial payments',
      question: 'Which orders still need collection?',
      icon: 'pending',
    ),
    ReportDefinition(
      id: 'payments_outstanding',
      category: ReportCategory.payments,
      title: 'Outstanding amount',
      question: 'What is total collection due?',
      icon: 'request_quote',
    ),
    ReportDefinition(
      id: 'payments_methods',
      category: ReportCategory.payments,
      title: 'Payment methods',
      question: 'How do customers pay?',
      icon: 'credit_card',
    ),
    ReportDefinition(
      id: 'payments_wallet',
      category: ReportCategory.payments,
      title: 'Wallet usage',
      question: 'How much store credit is issued?',
      icon: 'savings',
    ),
    // Suppliers
    ReportDefinition(
      id: 'suppliers_products',
      category: ReportCategory.suppliers,
      title: 'Products by supplier',
      question: 'Who sources which products?',
      icon: 'local_shipping',
    ),
    ReportDefinition(
      id: 'suppliers_activity',
      category: ReportCategory.suppliers,
      title: 'Supplier activity',
      question: 'How active is the supplier directory?',
      icon: 'insights',
    ),
    ReportDefinition(
      id: 'suppliers_recent',
      category: ReportCategory.suppliers,
      title: 'Recent suppliers',
      question: 'Who was added recently?',
      icon: 'add_business',
    ),
    ReportDefinition(
      id: 'suppliers_purchases',
      category: ReportCategory.suppliers,
      title: 'Purchase reports',
      question: 'What did we buy from each supplier?',
      icon: 'receipt_long',
      available: false,
    ),
    // Future — sales representatives (enabled via sales rankings)
    ReportDefinition(
      id: 'employees_performance',
      category: ReportCategory.employees,
      title: 'Sales by representative',
      question: 'Who closes the most business?',
      icon: 'badge',
      available: true,
      drillRoute: '/hub/orders',
    ),
    ReportDefinition(
      id: 'employees_visit_mix',
      category: ReportCategory.employees,
      title: 'Visit performance by rep',
      question: 'Who converts field visits into orders?',
      icon: 'groups',
      available: true,
      drillRoute: '/hub/visits',
    ),
    ReportDefinition(
      id: 'visits_coverage',
      category: ReportCategory.visits,
      title: 'Visit coverage',
      question: 'Are reps covering their routes?',
      icon: 'map',
      available: true,
      drillRoute: '/hub/visits',
    ),
    ReportDefinition(
      id: 'visits_conversion',
      category: ReportCategory.visits,
      title: 'Visit conversion',
      question: 'How often do visits turn into orders?',
      icon: 'trending_up',
      available: true,
      drillRoute: '/hub/visits',
    ),
    ReportDefinition(
      id: 'visits_collections',
      category: ReportCategory.visits,
      title: 'Collections per visit',
      question: 'Which visits collected payments?',
      icon: 'payments',
      available: true,
      drillRoute: '/hub/visits',
    ),
    ReportDefinition(
      id: 'visits_orders_per_visit',
      category: ReportCategory.visits,
      title: 'Orders per visit',
      question: 'How many orders come from each visit?',
      icon: 'receipt_long',
      available: true,
      drillRoute: '/hub/visits',
    ),
    ReportDefinition(
      id: 'visits_rep_performance',
      category: ReportCategory.visits,
      title: 'Representative visit performance',
      question: 'Who is converting field visits into orders?',
      icon: 'groups',
      available: true,
      drillRoute: '/hub/visits',
    ),
    // Schedules
    ReportDefinition(
      id: 'schedules_coverage',
      category: ReportCategory.schedules,
      title: 'Schedule coverage',
      question: 'How many planned visits fall in this period?',
      icon: 'event',
      available: true,
      drillRoute: '/hub/schedule',
    ),
    ReportDefinition(
      id: 'schedules_missed',
      category: ReportCategory.schedules,
      title: 'Missed stops',
      question: 'Which planned visits were missed?',
      icon: 'event_busy',
      available: true,
      drillRoute: '/hub/schedule',
    ),
    ReportDefinition(
      id: 'notifications_volume',
      category: ReportCategory.notifications,
      title: 'Notification volume',
      question: 'How busy is the in-app inbox?',
      icon: 'notifications',
      available: true,
    ),
    ReportDefinition(
      id: 'activity_feed',
      category: ReportCategory.notifications,
      title: 'Company activity',
      question: 'What happened across the business?',
      icon: 'timeline',
      available: true,
    ),
  ];

  static List<ReportDefinition> forCategory(ReportCategory category) => [
        for (final item in definitions)
          if (item.category == category) item,
      ];
}
